ТЗ 9 итерация 1
alexkiktev/java-filmorate pull request #3
Opened 2022-12-12 08:41 UTC by alexkiktev

2022-12-12 14:31 UTC, Frilock requested changes
Алексей, в целом хорошо, написал ряд небольших комментариев - жду новую версию.

2022-12-12 14:31 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    FilmService filmService = new FilmService();
Модификатор забыли

2022-12-13 04:22 UTC, alexkiktev commented on pom.xml
> +		<dependency>
Иван, не понял этот комментарий. Речь о том, что между тегами </dependency> и <dependency> не было пустой строки, верно? На всякий случай сделал Ctrl + Alt + L, но ничего в тексте не изменилось.
Убрал лишнюю зависимость - gson. Добавлял в процессе разработки, она не нужна в проекте (по крайней мере, пока).

2022-12-13 04:40 UTC, alexkiktev commented on pom.xml
> +            <version>2.9.0</version>
Исправил по вашему примеру. Если честно, не понял - версии всех используемых зависимостей нужно выносить в properties? Просто смотрю на пример наставника - там часть версий находится в properties, часть в самих зависимостях.
https://github.com/VladWild/person-web-service/blob/master/pom.xml

2022-12-13 04:42 UTC, alexkiktev commented on pom.xml
> +            <version>2.9.0</version>
Так же и с примерами в интернете - часть версий вынесены в properties, часть - нет.

2022-12-13 04:46 UTC, alexkiktev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping(value = "/films")
Готово

2022-12-13 04:48 UTC, alexkiktev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //обновление фильма
Готово

2022-12-13 04:53 UTC, alexkiktev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final Logger logger = LoggerFactory.getLogger(getClass());
Про аннотацию знаю, записывал ее себе в конспект. Использовал такое описание переменной, т.к. мне пока так понятнее)
Переделал.

2022-12-13 05:08 UTC, alexkiktev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Готово

2022-12-13 05:33 UTC, alexkiktev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (name == null || name.isBlank()) {
Спасибо, не знал о такой библиотеке. Переделал.

2022-12-13 05:36 UTC, alexkiktev commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    FilmService filmService = new FilmService();
Исправил.

2022-12-13 05:36 UTC, alexkiktev commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    UserService userService = new UserService();
Исправил.

2022-12-13 14:37 UTC, Frilock commented on pom.xml
> +		<dependency>
Вообще у меня отображались зависимости в разнобой, они должны быть на одном уровне, возможно это была проблема отображения

2022-12-13 14:38 UTC, Frilock commented on pom.xml
> +            <version>2.9.0</version>
Это не строгое замечание, просто я считаю, что так будет правильнее. Представим у Вас pom файл на 2000 строк, на мой взгляд, зависимости будет легче обновлять если они все в 1м месте

2022-12-13 14:40 UTC, Frilock approved these changes
Алексей, работу принял, на вопросы постарался ответить.

2022-12-18 17:38 UTC, merged